# Generated by Django 4.0 on 2022-03-28 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceapp', '0002_alter_planet_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='systems',
            field=models.ManyToManyField(to='spaceapp.StarSystem'),
        ),
    ]
