# Generated by Django 4.0 on 2022-03-26 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaceapp', '0003_user_planet_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atmosphere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h2', models.FloatField(default=0.0, verbose_name='водород')),
                ('he', models.FloatField(default=0.0, verbose_name='гелий')),
                ('h2O', models.FloatField(default=0.0, verbose_name='вода')),
                ('co2', models.FloatField(default=0.0, verbose_name='углекислый газ')),
                ('n', models.FloatField(default=0.0, verbose_name='азот')),
                ('o2', models.FloatField(default=0.0, verbose_name='кислород')),
                ('ar', models.FloatField(default=0.0, verbose_name='аргон')),
                ('other', models.FloatField(default=0.0, verbose_name='другое')),
            ],
        ),
        migrations.CreateModel(
            name='StarSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Звёздная система')),
            ],
        ),
        migrations.AddField(
            model_name='planet',
            name='orbit',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='planet',
            name='atmosphere',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spaceapp.atmosphere'),
        ),
        migrations.AddField(
            model_name='planet',
            name='starSystem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spaceapp.starsystem'),
        ),
    ]
